### ISSUE TITLE
Alumni dashboard

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#106]
Mapped out what we need to display in the dashboard for alumni roles. This can happen after all other dashboards are complete.

https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=1476040322

![screen shot 2017-07-26 at 11 33 44 am](https://user-images.githubusercontent.com/6525391/28632481-5118a108-71f6-11e7-955d-d7b5d62943e9.png)

**Comment by johjacb** [comment]
i believe this has been completed
