### ISSUE TITLE
Tie dashboard tabs to user

### ISSUE THREAD

**Issue by johjacb** [betheluniversity/portal#111]
Dashboards are currently hard coded and need to be changed to load programmatically

**Comment by tim-heck** [comment]
I think I got these working correctly. Also changed the applicant templates to be more like what the final versions will look like.

**Comment by johjacb** [comment]
thanks Tim. On the live site, I'm seeing extra dashboards under my account, such as 'CAPS applicant' and 'GS student'. Maybe I have extra roles applied?

Can we do some checking around to make sure this is functioning correctly?

**Comment by tim-heck** [comment]
So Josiah and I just dug into this and we believe that the live site is pulling roles from the live config.py rather than the actual user's roles.

**Comment by johjacb** [comment]
can you modify that?

**Comment by tim-heck** [comment]
I personally cannot since I don't have permissions at the moment, but I'll talk to Josiah.

**Comment by johjacb** [comment]
from Phil on slack : tim and I just changed the portal code so now the live page is pulling your roles from WSAPI instead of the local config. If you need to use testing roles again, just go to config.py and change DEVELOPMENT to True
