### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#12]
We decided we wanted breadcrumbs for portal tabs.

Also, possibly breadcrumbs for channels if we decide we're linking to channels as pages.

**Comment by c-schwarze** [comment]
Some notes on todos:

* Mobile view will include title.
* Full page channel will include breadcrumb.

**Comment by c-schwarze** [comment]
Updated, take a look at both links with respect to mobile and desktop views

1. https://portal.bethel.edu/deep_link_channel/?channel_path=/_blink-content/portal/channels/bethel-news&tab_title=Home
2. https://portal.bethel.edu

**Comment by c-schwarze** [comment]
@johjacb Any thoughts on styling this up?

**Comment by valehavenhomes** [comment]
the left margin of the title and breadcrumb should match the left margin of the channel i think

![screen shot 2017-04-26 at 3 26 26 pm](https://cloud.githubusercontent.com/assets/28057499/25455268/ca74fcda-2a94-11e7-83ac-f5912b2b7790.png)

**Comment by johjacb** [comment]
size/color look good. left margin on the title and breadcrumb should match the left margin on the channels below

![screen shot 2017-04-26 at 3 26 26 pm](https://cloud.githubusercontent.com/assets/2394337/25455490/a05b32a6-2a95-11e7-92f1-84b9e6add558.png)

**Comment by c-schwarze** [comment]
I updated the margin.

**Comment by e-jameson** [comment]
@c-schwarze @johjacb can we close this now?

**Comment by c-schwarze** [comment]
yeah
