### ISSUE TITLE
Look at rendering channels as pages

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#13]
J-mo is going to look into what it would take to render each channel as a page in the portal in case we wanted to have the ability to click on a channel and have it open as a page within the portal.

**Comment by c-schwarze** [comment]
I added a button on the channels to be able to render the channel as a page. The left most button (of the 4) will take you there. The url can then be taken to go to the page directly.

There is still some formatting to take care of, as some channels don't render for the whole page.

**Comment by kelslundberg** [comment]
This is looking good 👍  I showed the team and no updates needed so far....
