### ISSUE TITLE
Student View is single-column

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/portal#147]
I've been doing some testing with Emily's profile, and her Home and Student Academic tabs are single column. I had her confirm they are one column on the live site as well.

**Comment by e-jameson** [comment]
![image](https://user-images.githubusercontent.com/6525585/29476626-7f2771be-842a-11e7-9f39-2aad50248875.png)

**Comment by johjacb** [comment]
all pages besides the home page are doing this.

this is the result of a JS error. i've fixed it and that change will be rolling out soon
