### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#15]
We can start work on pulling in profile data for portal users:

https://docs.google.com/spreadsheets/d/1LQMvAwEcuNbKUIxMoRN8nRvALYRYj3A_HD8BmzKt_4k/edit#gid=652413578

Then we'll figure out how we want it to display.

**Comment by e-jameson** [comment]
I'm meeting with Derek tomorrow (4/12), I'll kick off getting data for this when I do.

**Comment by e-jameson** [comment]
@dstavem, I'm adding a high-priority label to this task so you know its the one we'd like done first.

**Comment by dstavem** [comment]
Questions:
1. How should I handle multiple programs/degrees/majors?  For example, do you want (a) one row per student with just the first program, (b) one row per student with a column for program_1 and program_2, or (c) two rows for a student with each program in a single column?
2. How should I handle people who have data in certain categories but not the role?  For example, I used to be a student, so if I pull up my program and degree, the MBA pulls up as most recent, but if I filter it by role, that program would not show up because I am no longer an active student.  Should I pull program for someone like me or pull a NULL?  My assumption is that I should probably pull a NULL for someone like me.
3. There is a field for "college" that indicates it is for roles of student and faculty.  I think it makes sense to have these as two separate fields, since a faculty member may also be a student, and the college may not be the same for each role.  Do you want these as one field or two?  If one, which I assume that the faculty college takes priority, but let me know if I am mistaken.
4. Am I correct that you are already pulling photo from somewhere else, or do you need me to include photo as part of this procedure?

That's all for now.
Derek

**Comment by e-jameson** [comment]
1. I'd say one row with multiple columns, or have them in one column with a separator, like a ; or something.

2. Someone like you should return a NULL

3. Lets try two fields here. If its not hard, could you give us the username of a person that would fall into a scenario like this that we can use to test?

4. We are already pulling photo, but it would be good to include it as part of this procedure. I can email you the SQL we are using right now, but it isn't 100% correct. I noticed my picture didn't update when I got a new ID card and photo a couple months ago.

Let me know if that all makes sense.

**Comment by dstavem** [comment]
I have created a procedure in **bth_portal_channel_api**.  It is called **bth_portal_channel_api.bu_profile**.

Feel free to take a look and let me know if you have questions so far.

I created 2 fields for degree, program, major, etc.

Class standing is currently pulling NULL because of a security issue with the function I used.

Also I still need to pull in job title and department.  However, some people may have more than one title/department again.  How would you like these handled?  Pick one?  Display as a list with a separator?

Derek

**Comment by e-jameson** [comment]
Thanks Derek, I'll take a look at these.

As far job titles, can we do a list with a separator? And is it possible to put the "main" one first?

**Comment by e-jameson** [comment]
Hey Derek, I'm working on updating the profile picture on the site to pull from the URL this procedure returns. It looks like the URL I'm getting currently isn't available in the browser.

The procedure is returning: bsp-nas.its.bethel.edu\\Departments\\StudentLife\\Public\\DataCard\\IDCentre\\Photos\\49553.jpg

We are currently loading: https://bsp-nas-dav.bethel.edu/IDCentre/Photos/49553.jpg

How difficult would it be to get the URL in the 2nd format? If its difficult I can translate it on my end.

Thanks!

**Comment by e-jameson** [comment]
Would we also be able to add ResBuilding and ResRoom like we are doing with the Wufoo Preload Common procedure for undergrad students?

**Comment by e-jameson** [comment]
Hey @dstavem any update on getting the profile photo updated, as well as getting Job and Residence info?

Thanks!

**Comment by dstavem** [comment]
I have not gotten back to this - how soon do you need it?  I'll try to work
within your time frame.  Thanks,

Derek


Derek Stavem
Systems Analyst
Enterprise Information Systems & Services
Bethel University
651.638.6723

**Comment by e-jameson** [comment]
We don't have a set deadline, sometime in the next few days would be great if possible so we can move on the other features.

Thanks

**Comment by dstavem** [comment]
Photo is now updated to match the format you gave.  I left the old one there to compare in case you have any issues.  The old one is labeled "photo_old."

**Comment by dstavem** [comment]
Residence info added.

I'll try to add job title/dept tomorrow.

Let me know if you see any issues.  Thanks!

**Comment by dstavem** [comment]
Sorry for the delays here.  I've now added title and dept for employees.  If there are more than one, they are in a single field separated with pipes.  Let me know if you have questions when you dig into things.  Thanks,

Derek

**Comment by e-jameson** [comment]
@johjacb can you take a look at this? All the data that we have is in there, I just don't really have a vision what it should look like. The HTML is in a Macro in this file:

https://github.com/betheluniversity/portal/blob/master/app/channels/profile_channel/profile.html

If we want to make any large changes let me know and I can assist.

**Comment by johjacb** [comment]
I think we need to decide what content we want first before we design it. our previous discussions have shown that we all have pretty different ideas about what some of these big sections should look like

**Comment by e-jameson** [comment]
@kelslundberg gave us a list of data in the original post. Did we talk about any content besides whats in that grid?

**Comment by kelslundberg** [comment]
We can certainly chat more on Tuesday! I'll add it to the list. This data mostly came from the current Academic Profile that's in Blink along with the addition of staff per our conversations.

![screen shot 2017-05-25 at 8 33 49 am](https://cloud.githubusercontent.com/assets/6525391/26452312/18d2bfa6-4125-11e7-8608-bad426de46b5.png)

**Comment by c-schwarze** [comment]
Hey Derek, I am seeing some issues with the data on this. Blink's Academic Profile channel differs from the Portal's profile on my program:

<img width="412" alt="screen shot 2017-05-30 at 2 04 36 pm" src="https://cloud.githubusercontent.com/assets/7849657/26600588/3f181546-4542-11e7-9dd5-88d5bfb23504.png">
<img width="455" alt="screen shot 2017-05-30 at 2 04 30 pm" src="https://cloud.githubusercontent.com/assets/7849657/26600587/3f1787a2-4542-11e7-9b2e-acc3e65cf1de.png">

**Comment by e-jameson** [comment]
Hey @dstavem, it also looks like username emj92698 (a CAS Senior) isn't getting any student data.

**Comment by e-jameson** [comment]
@johjacb I've added image and name to the profile page.

**Comment by kelslundberg** [comment]
@johjacb here's the list of data we had decided on pulling into the profile and then going from there as far as arrangement/formatting:
https://docs.google.com/spreadsheets/d/1LQMvAwEcuNbKUIxMoRN8nRvALYRYj3A_HD8BmzKt_4k/edit#gid=652413578

Do want me to put more structure to this? I could add headings to separate employee and student info? I could also add the links we talked about wanting to add to change your academic info and to IAM.

**Comment by johjacb** [comment]
@kelslundberg probably? kind of a big block of info right now. pretty dense too so breaking it up would make it easier to parse

**Comment by kelslundberg** [comment]
@johjacb what about something like this for organization? I sent it to Tim to take a peek at my categories...so he might have feedback

https://docs.google.com/spreadsheets/d/1LQMvAwEcuNbKUIxMoRN8nRvALYRYj3A_HD8BmzKt_4k/edit#gid=652413578

I was looking at my lifetime member profile area on my phone and desktop they sections broken up into channels...might work for something like this? They do have a few sparse channels, like we would have - what do we think about that? Just an idea! I'm not saying this is what we have to do :) :) 
![desktop-1](https://cloud.githubusercontent.com/assets/6525391/26637302/c18543bc-45e4-11e7-9409-888f98df2fe1.png)
![desktop-2](https://cloud.githubusercontent.com/assets/6525391/26637304/c19cf048-45e4-11e7-9c5a-db804d2ff07d.png)
![phone-1](https://cloud.githubusercontent.com/assets/6525391/26637310/c3b7edc4-45e4-11e7-861c-77ab5aefe629.PNG)
![phone-2](https://cloud.githubusercontent.com/assets/6525391/26637314/c556dc4e-45e4-11e7-8b97-9a5e50f66ebd.PNG)

**Comment by johjacb** [comment]
looks good

**Comment by kelslundberg** [comment]
sweet - @hamtim you think we can move forward with this direction? I'm cool if you're cool - I'm sure we'll be able to move a couple things around/add a link/update wording if needed once we see it in this format.

**Comment by hamtim** [comment]
I'm cool with this direction @kelslundberg and @johjacb

**Comment by dstavem** [comment]
@c-schwarze @e-jameson 

I think the student data issue is now fixed.  You may need to double check your tags/labels as I changed some of them.  The problem was that I was pulling program 1 and 2, but some program 2 items were still labeled as 1.  Let me know if you have questions.  Thanks!

**Comment by josiahtillman** [comment]
Here's how the profile page looks! Let me know if you guys think any other changes should be made.

![screen shot 2017-06-21 at 4 15 47 pm](https://user-images.githubusercontent.com/12627410/27407173-ff62cc86-569c-11e7-83d0-862ced6ae678.png)

**Comment by kelslundberg** [comment]
Thanks for working on breaking this up into sections @josiahtillman! We looked at it during our meeting yesterday and @johjacb is going to work with you a bit on refining it. 

Also, we'd like to add email address underneath ID# and then add a placeholder link below it that says "Update password and account"

**Comment by kelslundberg** [comment]
Let's aim to have this finalized before HR meeting on Thursday, July 8.

**Comment by johjacb** [comment]
I've made an update

**Comment by josiahtillman** [comment]
Sorry the email hasn't been added yet. For some reason, it isn't being pulled for the user data. I'll keep working on it and get back to you guys later.

**Comment by johjacb** [comment]
i've added the email address and an 'edit info' button

**Comment by kelslundberg** [comment]
Super! Thanks, @johjacb 

I think the button can link here: https://iam.bethel.edu/

**Comment by c-schwarze** [comment]
The change academic info button should be changed to only display to CAS students.

@tim-heck could you add this when you have a chance?

**Comment by kelslundberg** [comment]
Change academic info button can go here:
https://www.bethel.edu/registrar/forms/change-of-major-minor

**Comment by kelslundberg** [comment]
Also, can we change the text on the Edit info button underneath the email address to say "Update email account"

**Comment by tim-heck** [comment]
I've changed the 'change academic info' button to only be viewed by CAS students, added the link to that button, and changed the text of the 'Edit info' button to be 'Update email account'

**Comment by johjacb** [comment]
work completed. closing issue
