### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#18]
J-mo was going to get started on pulling the existing enrollment checklist into the portal and we'll go from there :)

**Comment by e-jameson** [comment]
This has data, I'm using username mws25934 to pull in the checklist.

**Comment by kelslundberg** [comment]
Vedmic wants this moved to the top content area where the checklist is to see what it looks like when the checklist is this long.

**Comment by kelslundberg** [comment]
When the enrollment checklist isn't active, we should have a message reading:

Your enrollment checklist will be active on _month date, year_.

Your enrollment checklist will be active on April 11, 2017.

**Comment by c-schwarze** [comment]
@johjacb I added the current checklist to the dashboard.

**Comment by johjacb** [comment]
can you strip out the old style classes (uportal) and convert to Bootstrap's classes?

**Comment by c-schwarze** [comment]
Updated.

Let me know if you want me to do anything else.

**Comment by johjacb** [comment]
thanks for removing the classes. 

I should've been more detailed in more previous request. Can you also strip out all extras, such as align="center", border=0, <br> etc?

thanks

**Comment by c-schwarze** [comment]
Updated.

**Comment by johjacb** [comment]
great - looks good. I see a few < br > s in there, could you remove those too? Thanks

**Comment by c-schwarze** [comment]
Done

**Comment by johjacb** [comment]
Could you change the icons to use the ones included with the theme? thanks.
let me know if you need help with this

**Comment by c-schwarze** [comment]
I added in the new icons.

**Comment by kelslundberg** [comment]
@c-schwarze should we close this one since we have the new one open - or do you want to keep this one open as well?

**Comment by c-schwarze** [comment]
Yeah lets close this
