### ISSUE TITLE
Confirm portal works when a channel fails

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/portal#19]
We need to confirm that the Portal will work correctly when a single channel doesn't work. This channel should have some sort of error message on what to do. We should confirm by having channels randomly fail for a while like we did on the dashboard.

**Comment by c-schwarze** [comment]
This should be working. If we randomly cause one to fail, it will only occur from one possible error.

I will go ahead and add some channels that are missing values, have incorrect values, an unhandled type, or bad data.

**Comment by c-schwarze** [comment]
I will leave the 4 extra broken channels in. we can remove them whenever.
