### ISSUE TITLE
Course list channel

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#22]
We're needing a channel that pulls in active courses for students:

Based on our meeting today, we're thinking:
- Pulls active courses from Banner
- Links to the course in Moodle if there's a Moodle course (no link if the course is not in Moodle)
- A link to past courses

Let me know if you need any more details or have any questions!

**Comment by kelslundberg** [comment]
FYI - The registrar loves this idea...

They also want to keep links into SSB for:

Week at a Glance
Student Detail Schedule

It makes sense to me that these to links go along with this channel. Maybe a section below the course list? These links are currently in the Registration Tools channel.

**Comment by c-schwarze** [comment]
I am putting some code here so it doesn't get lost. Feel free to ignore:
```
global $DB;
$user = $DB->get_record('user', array('firstname'=>'Caleb', 'lastname'=>'Schwarze'));
$userId = $user->id;
$userEnrolments = $DB->get_records('user_enrolments', array('userid'=>$userId));

$coursesArray = array();
foreach( $userEnrolments as $userEnrolment ){
        $userEnrolmentsId = $userEnrolment->enrolid;
        $enrol = $DB->get_record('enrol', array('id'=>$userEnrolmentsId));
        $courseId = $enrol->courseid;
        $course = $DB->get_record('course', array('id'=>$courseId));
        $courseName = $course->fullname;
        if( $course->visible == 1 ) {
                array_push($coursesArray, $courseName);
                print_r($course->visible);
        }
}

print_r($coursesArray);
```

**Comment by kelslundberg** [comment]
Sample channel here:
https://portal.bethel.edu/student-academics

@c-schwarze should I open a separate issue for the faculty active courses channel since that has some different info/links associated with the courses?

**Comment by c-schwarze** [comment]
Yeah that would be great

**Comment by e-jameson** [comment]
I ran this by Lisa this morning and and getting the courses shouldn't be a problem. I mentioned pulling in course URLs to Moodle and she said that might be more challenging, but probably do-able. Derek's done the most work on pulling Moodle data into Banner so we'll talk with him next week.

**Comment by e-jameson** [comment]
I met with Derek and he's going to work on this and get data it to us in the next week or so.

**Comment by kelslundberg** [comment]
@e-jameson - checking in to see if we have any updates here - I'd love to be able to meet with Registrar last week of July if possible

**Comment by dstavem** [comment]
@kelslundberg  @e-jameson  I'm just working on this now - hope to have something by tomorrow. D

**Comment by dstavem** [comment]
Can you clarify what you mean by "active courses"?  For example, should this include all courses for a particular term, even though some might start in a later block in that term (relevant for CAPS/GS in particular)?  Similarly, near the end of a term, when should it include courses for the upcoming term?  I think CAPS/GS currently expects that courses be made available in Moodle 2 weeks ahead of the course start date (and seminary will likely start with this expectation in fall), but CAS likely does not have that same structure.  Let me know your thoughts on dates and which courses to show.  Thanks!

**Comment by e-jameson** [comment]
I talked to Derek and we are going to add courses to the list 2 weeks before they start, and keep courses in the list 2 weeks after they end. For all schools.

**Comment by kelslundberg** [comment]
I think that sounds like an excellent plan - thanks for chatting on this!

**Comment by dstavem** [comment]
See bth_portal_channel_api.class_list_stu for this info.  For now, I have more info included than you requested in case you find you need some of it.  I can remove some of this once you feel confident you have what you need.  To create the link to Moodle, use the field tagged "mdl_crse_id."

Let me know if you have questions as you start looking through this.  Thanks!

Derek

**Comment by kelslundberg** [comment]
Thanks, Derek!!!!!!

**Comment by dstavem** [comment]
Do you have students that you are testing with who are currently enrolled?  If not, here are some netid's of some students that I was using in testing: amh56249, jak78447, jau33459, dab48593.

**Comment by kelslundberg** [comment]
@c-schwarze is this one set up? I see links added for the Faculty Course List channel, but not the student one:

https://portal.bethel.edu/deep_link_channel/c0af22cb8c586513543f13a693f6a8b9/student%20academics

**Comment by e-jameson** [comment]
We have the data just need to build this out out quick. @c-schwarze can you do this if you have time early this week?

**Comment by c-schwarze** [comment]
This is merged into master. It is currently pulling from the user: "amh56249". We will need to swing back to this and fix the username to be the user's current user.

**Comment by kelslundberg** [comment]
Thanks! Were we able to get moodle links for courses? Or doe these courses not have moodle sites?

**Comment by e-jameson** [comment]
Hey @dstavem would it be possible to add the `mdl_crse_id` column to the `bth_portal_channel_api.class_list_stu` procedure?

**Comment by dstavem** [comment]
It should already be there - let me know if you're not seeing it.

**Comment by e-jameson** [comment]
Yup I'm just blind or something. Sorry about that.

**Comment by e-jameson** [comment]
I added course links to the class list. I linked the course title. Little cleaner, imo, since we don't have a full list of links at the bottom like the faculty channel

**Comment by kelslundberg** [comment]
Registrar is reviewing - meeting with them on Tuesday after the portal meeting

**Comment by kelslundberg** [comment]
Ready for testing!

**Comment by d-freed** [comment]
My first test with Emily Johnson turned up weird. Her Active Courses channel showed two classes, but she is registered for 4. And neither of the classes are correct. Is this channel still using dummy data?

**Comment by d-freed** [comment]
@kelslundberg another test with Kathryn Magnuson was successful, it showed the correct classes in the channel.

**Comment by e-jameson** [comment]
The `Student Detail Schedule` and `Week at a Glance` URL's in this channel do not go through Banner's SSO. @c-schwarze or @dstavem do you know if this is something that will be fixed once Banner 9 goes live, or should we wrap the URLs in the Banner SSO Manager?

**Comment by e-jameson** [comment]
I've updated the links to be wrapped in the SSO Manager

**Comment by c-schwarze** [comment]
Seems to be working just fine. Closing.
