### ISSUE TITLE
Leave report and time sheet reminders

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#25]
It sounds like if Derek has time, we'd love to work on pulling data for leave report and time sheet reminders.

If I remember the logic correctly, it sounds like this is dependent on knowing if someone is exempt or hourly in order to pull the proper reminder (Leave Report Due or Time Sheet Due). I'm not sure if hourly folks have Leave Reports as well or if they only have time sheet reminders?

We'd want the reminder to display 5 days before it's due (I'm guessing that it's due last day of the month?) and then go  away after it's complete.

Please let me know if there are any more details needed to get started!

**Comment by e-jameson** [comment]
@dstavem assigning you to this one. Gregg O. started working on this a while back. He has two procedures created for it: 

- bth_portal_channel_api.supervisor_timesheet
- bth_portal_channel_api.employee_timesheet

The channels we are looking to crecreate are Time Reporting Reminders and Time Approval Reminders on the Work Life Tab.

Setting to medium priority for now, as we are working on the Profile first. When you do have time to work on this one let me know and we can talk details.

**Comment by e-jameson** [comment]
I think we have all we need for this. Marking as done
