### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#30]
Vedmic is telling people this will be an app on their phones - so we're needing to find the best way to make that happen :)

**Comment by c-schwarze** [comment]
portal.bethel.edu has an example of a solution to this. It can only be seen on mobile and has some settings we are able to play around with. http://cubiq.org/add-to-home-screen

Lets take a look at this on Monday, if we have time.

**Comment by c-schwarze** [comment]
The settings can be changed, if we want them to be. The current settings are: 

* not mandatory
* appear 3 times (can only receive it once per day)
* it will try to not show up after they choose to 'add to homescreen'
* it will remain on the screen until they click away or 'add to homescreen'

**Comment by c-schwarze** [comment]
@johjacb addtohomescreen.js needs to have a good amount of icons created. Let me know if you think its reasonable to have all of these images or if we need to modify their code to do it more automatically.

```
    <link rel="apple-touch-icon" sizes="57x57" href="/static/dist/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/static/dist/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/dist/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/dist/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/dist/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/static/dist/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/dist/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/static/dist/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/dist/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/static/dist/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/dist/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/static/dist/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/dist/favicons/favicon-16x16.png">
```

**Comment by johjacb** [comment]
i've added this list previously. should be there in the <head>

**Comment by c-schwarze** [comment]
Okay I added back these images/favicons that were missing.

This should be good to go, we will just need to talk about settings down the road. I will leave this in the 'review' category for now.
