### ISSUE TITLE
Long channel names

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/portal#35]
Currently, if a channel name is too long it pushes the settings (top right corner of the channel) down.

If a channel title is too long, I would say we either develop a way to wrap the title, or we add '. . .' to the end of the title.

**Comment by e-jameson** [comment]
I'm going to update the data-def to limit titles to 30 characters. At 30 its currently not working, but thats about the longest title we currently have in Blink.

@johjacb can you take a look at the style to make sure a 30-character title functions well? Tablet-view seemed the most problematic when I was testing.

**Comment by e-jameson** [comment]
Nevermind, can't set a character limit unless we change the data definition. Jake is there a way we can wrap the title better?

**Comment by c-schwarze** [comment]
This is fixed! just had to properly pull the css updates from ages ago
