### ISSUE TITLE
Keep channel collapse/toggle settings

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#41]
This is low priority.

It would be great to keep someone's settings if they've decided to close/collapse certain channels on their screen. So if they toggle a channel closed it would stay closed until they toggle the channel back open...

Toggle is a funny word :)

**Comment by e-jameson** [comment]
I started working on an implementation for this. It uses JS so you can see the channels collapse when the page is loading. We could try using the Python session and POST requests to have the backend be aware of which state to load them in.

**Comment by e-jameson** [comment]
Bug: This doesn't work correctly if there are two of the same channel (same HTML ID).

**Comment by c-schwarze** [comment]
This code needs to be rewritten since we reworked the html

**Comment by johjacb** [comment]
not going to implement this feature
