### ISSUE TITLE
Full screen display for all channels

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#42]
We need all channels to be able to fit full screen/width.

**Comment by c-schwarze** [comment]
This works now!

Do any channels need any extra work? or can this be closed?

**Comment by kelslundberg** [comment]
I did some testing and it's looking good to me. I'd say we can close and then test this feature on new channel types and report any bugs if we notice them?

**Comment by c-schwarze** [comment]
Sounds good.
