### ISSUE TITLE
HR news

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#44]
HR would like to keep their channel for HR news - so we'll need to pull that into a channel:

https://cms.bethel.edu/entity/open.act?id=2964e0c58c5865133973dd3eb5b1cc71&type=folder&

They also asked about being able to target HR news to student employees and San Diego staff. I think we talked about one channel with three targeted sections.

Would we prefer to set everything for that up at the same time or can we start with the current HR news channel and then add the sections to it later?

**Comment by e-jameson** [comment]
@kelslundberg, I think lets set it up as-is for now and add the sections later.

@c-schwarze do you think its worth making a more general "News Channel" at this point?

**Comment by c-schwarze** [comment]
Maybe. How would we distinguish HR news from news articles? We could pass parameters with the Class path for the channel in cascade. 

I would be fine if they merged, since we would probably share the same template anyway.

**Comment by e-jameson** [comment]
Currently the news channel has a URL that it calls to get the feed. I was thinking we move this to Cascade as a Parameter for a News Channel, and have one Python class that finds the URL and embeds it. Thoughts?

**Comment by c-schwarze** [comment]
That sounds good. Should this field be a more generic 'options' field in the channel data def?

**Comment by e-jameson** [comment]
I added a News Channel type and created an HR news channel. Its the same HTML as current Blink, so it needs some work, and we'll also have to update it when we break it out into sections.

**Comment by e-jameson** [comment]
Closing this for now. @kelslundberg if we want to split HR News into more sections later, lets open a new request to develop that.
