### ISSUE TITLE
Refresh Channel button

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/portal#45]
It might be helpful to add a button to each channel that reloads the content of the channel. If we go ahead with the cache option (#36), I think it would be helpful to be able to refresh a channel on click.

Adding low priority.

**Comment by c-schwarze** [comment]
Needs some more styling.

Currently the functionality is broken until #84 is fixed

**Comment by c-schwarze** [comment]
#84 is fixed, so only styling is needed.

**Comment by johjacb** [comment]
looks like there may be some significant JS challenges to getting this working, especially if the content resizes on refresh, which could trigger a layout reflow. 

can we get by with it?

**Comment by c-schwarze** [comment]
Bummer. I'll add it as a topic of next weeks portal meeting.

**Comment by johjacb** [comment]
closing for now. reopen if necessary
