### ISSUE TITLE
Create a way to test various roles and act as users

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/portal#51]
We should add a 'Admin only' menu option that allows a user to view the portal as a specific user, or for a specific role (maybe have a select field to choose any combination of roles?).

**Comment by c-schwarze** [comment]
Here is what I am thinking, but I want to talk this through being developing much of this.

We should add a drawer for admin options. Admins should be able to go to a separate page with 2 options: view portal by username and view portal by roles. Username will be a write-in and roles will be a select field. Once you click 'View', you will be redirected to the homepage and see what that user sees, except there will be a banner at the top that says you are viewing the portal based on username/roles with a button to revert.

**Comment by c-schwarze** [comment]
@e-jameson and @hamtim, I talked with Kelsey but she wanted me to double check with you guys on this. Does my comment above sound like a good idea?

**Comment by e-jameson** [comment]
I think this is a great idea. Do you think its worth selecting which role-set you want, instead of just one at a time?

**Comment by c-schwarze** [comment]
I talked with Kelsey and she thought that if someone was going to be specific enough with multiple roles, they would have a username.

**Comment by e-jameson** [comment]
That makes sense to me.

**Comment by c-schwarze** [comment]
I added a basic way to test this out. I didn't want to style it up too much, in case we change the idea.

In the side nav, under the tabs, go to 'Admin' (portal.bethel.edu/admin). This will then take you to act as a different user or role.

**Comment by kelslundberg** [comment]
Thanks so much! I'll add this to the agenda for Monday.

**Comment by e-jameson** [comment]
I tested this. Worked great viewing Emily's account, but I got stuck in her account even after clicking "return to your account"

**Comment by c-schwarze** [comment]
This should be fixed. The issue was the session not properly clearing on production

**Comment by kelslundberg** [comment]
I'm not seeing any roles in the dropdown at the moment.

I did add a role this morning, so I'm wondering if that affected this?

![screen shot 2017-06-06 at 8 50 01 am](https://cloud.githubusercontent.com/assets/6525391/26832467/30fdc3f4-4a95-11e7-9149-b07db05c716c.png)

**Comment by c-schwarze** [comment]
Oops. That was a hiccup from me changing the portal cascade roles id. Should be fixed now

**Comment by c-schwarze** [comment]
This works, but it should be styled up.

**Comment by kelslundberg** [comment]
Can we add a link to return back to Admin when viewing other roles/accounts? I figure it'll make testing a little quicker?

**Comment by c-schwarze** [comment]
Great suggestion. Absolutely.

**Comment by tim-heck** [comment]
I finished styling some of this and added the link to return to the admin page when testing, should be on the live site.

**Comment by c-schwarze** [comment]
Closing
