### ISSUE TITLE
Event Feeds - create new feeds that have the corresponding categories

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/portal#76]
The plan is to build these out in Cascade and then simply link the those from cascade through channels.

**Comment by c-schwarze** [comment]
I added a folder in Cascade: /_blink-content/portal-content/event-feeds, which will hold the event feed blocks and the pages that hold them. These pages will need to be published and then included in the corresponding channels

**Comment by kelslundberg** [comment]
I think these are working just great! I'm going to leave this opened and assigned to me until I've finished getting these set up.

**Comment by kelslundberg** [comment]
@c-schwarze created a new portal event feed - so I'm working on getting these set up

**Comment by c-schwarze** [comment]
I believe these are set up.

Closing. Let me know if this needs to be reopened

**Comment by kelslundberg** [comment]
Thanks @c-schwarze - do I have this set up correct or do I need to do something else....

https://cms.bethel.edu/entity/open.act?id=cb8e4f148c586513260ac2972212a3e2&type=block&
https://portal.bethel.edu/deep_link_channel/cb8e4f148c586513260ac2972212a3e2/home

Sorry if I missed how to do this :)

**Comment by c-schwarze** [comment]
@kelslundberg so we are going to leverage the current Blink event channel. Down the road, we can use the ones that are being used on the dashboards.

I changed the path to the current Blink path as well.

**Comment by c-schwarze** [comment]
Closing
