### ISSUE TITLE
Can't delete tabs

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#90]
I tried deleting the Employment tab in cascade and I'm not able to delete it. It's giving me an error saying "no outputs selected" but I'm not able to select any outputs.

Thanks!!

**Comment by e-jameson** [comment]
@kelslundberg can you show me what happens when you try and delete a tab today after our meeting?

**Comment by c-schwarze** [comment]
Is this still having issues?

**Comment by kelslundberg** [comment]
yeah I just tried to delete Employment tab

**Comment by c-schwarze** [comment]
@josiahtillman when you have a chance, can you look at this?

**Comment by josiahtillman** [comment]
So it looks like @kelslundberg figured this one out-- if you uncheck "unpublish content" you can submit the deletion. Then, if the portal xml is republished, the tabs will be removed.
