### ISSUE TITLE
Tools & Resources

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#91]
@vedmic any update on icons for this?

https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=1449065714

**Comment by kelslundberg** [comment]
A couple things here:

We decided to remove bullet points.

Some icons aren't showing. Most of them should be referencing fa icons and a few are pulling in images directly from Cascade. Let me know if there's anything you need me to do here or change!

**Comment by johjacb** [comment]
I think we should remove the icons on the sidenav. Check out the readability of the two lists. the icons seem to add more visual noise that outweighs any benefit that they provide

 I also think we should consider alphabetizing the list

![screen shot 2017-07-10 at 11 00 56 am](https://user-images.githubusercontent.com/2394337/28027609-40b718ce-655f-11e7-9be9-c86a0f4029f4.png)
![screen shot 2017-07-10 at 11 01 11 am](https://user-images.githubusercontent.com/2394337/28027610-40bb02f4-655f-11e7-869b-db2533d8d095.png)

**Comment by kelslundberg** [comment]
I'm fine with this - added it to the agenda for today.

**Comment by johjacb** [comment]
i've pushed out a basic version. calls out the google suite, as well as moodle, banner and offices

**Comment by johjacb** [comment]
closing for now. reopen if more work needs to be done
