### ISSUE TITLE
Facebook Channel not Responsive

### ISSUE THREAD

**Issue by josiahtillman** [betheluniversity/portal#92]
The Facebook channel gets its size set when the page loads, but then doesn't change when the window is resized. This is an issue on Facebook's end that we cannot fix through our css or javascript. Our only option would be to reload it whenever the window size changes.

Example:
![screen shot 2017-07-05 at 2 26 54 pm](https://user-images.githubusercontent.com/12627410/27881391-116f892c-618e-11e7-8e9c-0c6aa61091bd.png)
And then after resizing:
![screen shot 2017-07-05 at 2 27 12 pm](https://user-images.githubusercontent.com/12627410/27881402-18f65f18-618e-11e7-809c-dd8617acea95.png)

**Comment by johjacb** [comment]
@c-schwarze assigning to you, to decide who to assign it to

**Comment by kelslundberg** [comment]
Closing and combining it with issue #77
