### ISSUE TITLE
CAS Student Dashboard

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#93]
We decided on a set of premier icons and a Today's Event feed with categories that are CAS-student specific.

@vedmic is working on getting icons - icons needed and links are on the grid:
https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=1857012922

@hamtim is going to check the calendar categories for me (also on the grid):
https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=1857012922

**Comment by kelslundberg** [comment]
Event feed is here:
https://cms.bethel.edu/entity/open.act?id=3c3a43c28c586513260ac29776e34f27&type=page&

**Comment by johjacb** [comment]
i pushed out a design for this. icons are still under construction

**Comment by kelslundberg** [comment]
Looks like we still need to add the links here:

Academics - link to Student Academics tab
Athletics - https://athletics.bethel.edu/
BSG - https://www.bethel.edu/undergrad/bsg/
Clarion - https://bethelclarion.com/
Arts - https://www.bethel.edu/events/arts/
Today's menu - https://www.bethel.edu/dining-services/locations/monson/menu-file/weekly-menu.html

**Comment by bak45247** [comment]
done
