### ISSUE TITLE
Testing Tab/Page

### ISSUE THREAD

**Issue by josiahtillman** [betheluniversity/portal#94]
We want to get rid of the Testing tab in Portal so that we can move closer to what the real thing might look like. However, the developers do still need a place to test out new channels. We could probably add this to be one of the links in the after clicking "Admin" under "Tools & Resources." The tab/page would then be out of the way, but still accessible for the developers.

**Comment by c-schwarze** [comment]
What if we added a new 'DEVELOPER' role to the tab, and then we can just have a list in the config of usernames who should get the 'DEVELOPER' role in the user_roles portion of the session.

Thoughts? @josiahtillman @phg49389 @e-jameson

**Comment by c-schwarze** [comment]
This is up and working. We added it as an option in the admin interface.
