### ISSUE TITLE
CAS Applicant Dashboard

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#95]
Got the CAS applicant dashboard mapped out here. Please let me know if you have any questions for me!

https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=412174702
![screen shot 2017-07-11 at 10 08 28 am](https://user-images.githubusercontent.com/6525391/28075379-e87b153a-6620-11e7-82dc-2173c083cd38.png)

**Comment by ErikGruber** [comment]
Hi @c-schwarze - here's content to start with. It might be long, but we can cut once we see what it looks like. https://docs.google.com/document/d/1hWRCYZw7E9ymVzTozpnrF-PqMLhJbG7mrRF7u8tCuf8/edit

**Comment by kelslundberg** [comment]
Event feed is here:
https://cms.bethel.edu/entity/open.act?id=3c3647ac8c586513260ac29786fad731&type=page&

**Comment by kelslundberg** [comment]
Looks like we still need links for the buttons:

VISIT: https://www.bethel.edu/undergrad/admissions/visit/
MAPS: https://www.bethel.edu/about/maps-directions/
PAY YOUR ENROLLMENT DEPOSIT: https://www.bethel.edu/undergrad/admissions/enroll/deposit
VIEW MY ENROLLMENT CHECKLIST: Link to Checklist tab

**Comment by bak45247** [comment]
DONE
