### ISSUE TITLE
CAPS Applicant Dashboard

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#96]
Got the CAPS applicant dashboard mapped out here. Let me know if you have any questions for me!

https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=412174702
![screen shot 2017-07-11 at 10 09 31 am](https://user-images.githubusercontent.com/6525391/28075447-238870d2-6621-11e7-9e5c-2055b7bad384.png)

**Comment by ErikGruber** [comment]
@c-schwarze here's a link to content you can get started with. It might be a bit long, but I figured we can see what it looks like and go from there - https://docs.google.com/document/d/1U9dqbw1imfxFU43vfGuWBhpRi99MPAuzmkBWtc1U8t4/edit

**Comment by kelslundberg** [comment]
Event feed is here:
https://cms.bethel.edu/entity/open.act?id=3cd08d308c586513260ac29777d44a04&type=page&

**Comment by kelslundberg** [comment]
Looking real good!

It looks like we still need to link up the Maps and Visit buttons - all dashboard links are here:

https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=107701472

OR here are the links for these specific buttons:

VISIT: https://www.bethel.edu/adult-undergrad/admissions/visit/
MAPS: https://www.bethel.edu/about/maps-directions/
CONFIRM YOUR ENROLLMENT: https://www.bethel.edu/adult-undergrad/admissions/enroll

**Comment by bak45247** [comment]
done
