### ISSUE TITLE
GS Applicant Dashboard

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#97]
Got the GS applicant dashboard mapped out here. 

Forgot to mention, Erik is still working on messaging for welcome message and enrollment status stuff. Hope that is okay!

https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=412174702
![screen shot 2017-07-11 at 10 10 52 am](https://user-images.githubusercontent.com/6525391/28075519-5592ba56-6621-11e7-84c8-3a3dd5ead20b.png)

**Comment by ErikGruber** [comment]
Hey @c-schwarze here's a link to content you can get started with. It might be a bit long, but I figured we can see what it looks like and go from there - https://docs.google.com/document/d/1yWyi2CJIbsqznH3M07LwW2bZCofCo5g-UakB64m12zY/edit

**Comment by kelslundberg** [comment]
Event feed is here:
https://cms.bethel.edu/entity/open.act?id=3cd4f19b8c586513260ac297540fec4a&type=page&

**Comment by kelslundberg** [comment]
Looks good!

Need to add links here too:

VISIT: https://www.bethel.edu/graduate/admissions/visit/
MAPS: https://www.bethel.edu/about/maps-directions/
CONFIRM YOUR ENROLLMENT: https://www.bethel.edu/graduate/admissions/enroll

**Comment by bak45247** [comment]
got it
