### ISSUE TITLE
SEM Applicant Dashboard

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/portal#98]
Got the seminary applicant dashboard outlined here. Erik is still working on exact messaging.

Let me know if you have questions for me!

https://docs.google.com/spreadsheets/d/1vbzNXjBz2dVc8ZdH61bNolWzgZfW2GzEzoR9a92w06M/edit#gid=412174702
![screen shot 2017-07-11 at 10 12 11 am](https://user-images.githubusercontent.com/6525391/28075593-8b86eaf6-6621-11e7-9cbf-4010f362a2e6.png)

**Comment by ErikGruber** [comment]
Hi @c-schwarze, here's a link to content you can get started with. It might be a bit long, but I figured we can see what it looks like and go from there - https://docs.google.com/document/d/1ryyTeI4FKNJidOHcfY_IYUxJ73An7EUDPZ16pYOShSM/edit

**Comment by kelslundberg** [comment]
Event feed is here:
https://cms.bethel.edu/entity/open.act?id=3cd75ded8c586513260ac2971c33a61b&type=page&

**Comment by kelslundberg** [comment]
Looking good!

We still need to link up the buttons:

VISIT: https://www.bethel.edu/seminary/admissions/visit/
MAPS: https://www.bethel.edu/about/maps-directions/
CONFIRM YOUR ENROLLMENT: https://www.bethel.edu/seminary/admissions/enroll

**Comment by bak45247** [comment]
done
